# Generated by Django 2.2.10 on 2020-02-27 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('cms_forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_forms_formfield', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(max_length=255)),
                ('field_type', models.CharField(max_length=255)),
                ('field_parameters', models.TextField(default='{}')),
                ('widget_type', models.CharField(blank=True, default=True, max_length=255)),
                ('widget_parameters', models.TextField(default='{}')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
