# Generated by Django 2.2.10 on 2020-03-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_forms", "0004_auto_20200307_1719"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="form_type",
            field=models.CharField(default="django.forms.forms.Form", max_length=255),
        ),
    ]
