# Generated by Django 2.2.10 on 2020-03-08 00:01

import cms_forms.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms_forms", "0005_form_form_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formfield", name="field_parameters", field=cms_forms.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="formfield", name="widget_parameters", field=cms_forms.fields.JSONField(default=dict),
        ),
    ]
