# Generated by Django 2.2.10 on 2020-03-08 20:14

import cms_forms.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("cms_forms", "0007_auto_20200308_2047"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormWidget",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="cms_forms_formwidget",
                        serialize=False,
                        to="cms.CMSPlugin",
                    ),
                ),
                (
                    "widget_type",
                    cms_forms.fields.TypeReferenceField(blank=True, default=None, max_length=255, null=True),
                ),
                ("widget_parameters", cms_forms.fields.JSONField(blank=True, default=dict)),
            ],
            options={"abstract": False,},
            bases=("cms.cmsplugin",),
        ),
        migrations.RemoveField(model_name="formfield", name="widget_parameters",),
        migrations.RemoveField(model_name="formfield", name="widget_type",),
        migrations.AlterField(
            model_name="form",
            name="form_type",
            field=cms_forms.fields.TypeReferenceField(default="django.forms.forms.Form", max_length=255),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="field_type",
            field=cms_forms.fields.TypeReferenceField(default="django.forms.fields.Field", max_length=255),
        ),
    ]
