# Generated by Django 2.2.10 on 2020-03-08 20:23

import cms_forms.fields
import cms_forms.importer
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms_forms", "0008_auto_20200308_2114"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="form_type",
            field=cms_forms.fields.TypeReferenceField(
                default=cms_forms.importer.TypeReference("django.forms.forms.Form"), max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="field_type",
            field=cms_forms.fields.TypeReferenceField(
                default=cms_forms.importer.TypeReference("django.forms.fields.Field"), max_length=255
            ),
        ),
    ]
