# Generated by Django 2.2.10 on 2020-03-09 20:48

import cms_forms.fields
import cms_forms.importer
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("cms_forms", "0009_auto_20200308_2123"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChoiceOption",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="cms_forms_choiceoption",
                        serialize=False,
                        to="cms.CMSPlugin",
                    ),
                ),
                ("value", models.CharField(blank=True, default="", max_length=255)),
                ("display", models.TextField(blank=True, default="")),
            ],
            options={"abstract": False,},
            bases=("cms.cmsplugin",),
        ),
        migrations.AlterField(
            model_name="formwidget",
            name="widget_type",
            field=cms_forms.fields.TypeReferenceField(
                default=cms_forms.importer.TypeReference("django.forms.widgets.Widget"), max_length=255
            ),
        ),
    ]
