# Generated by Django 2.2.10 on 2020-03-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_forms", "0010_auto_20200309_2148"),
    ]

    operations = [
        migrations.AddField(model_name="form", name="auto_render_fields", field=models.BooleanField(default=False),),
        migrations.AddField(model_name="form", name="lazy_loaded", field=models.BooleanField(default=True),),
    ]
