# Generated by Django 2.2.10 on 2020-03-11 18:54

import cms_forms.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms_forms", "0012_auto_20200309_2309"),
    ]

    operations = [
        migrations.AddField(
            model_name="form", name="meta_parameters", field=cms_forms.fields.JSONField(blank=True, default=dict),
        ),
    ]
