# Generated by Django 2.2.10 on 2020-03-14 13:14

import cms_forms.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_forms", "0013_form_meta_parameters"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("form_name", models.CharField(max_length=255)),
                ("data", cms_forms.fields.JSONField(blank=True, default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
